ALTER TABLE user_progress 
ADD COLUMN IF NOT EXISTS is_reserve BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS srs_next_review TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS srs_interval INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS srs_ease FLOAT DEFAULT 2.5;
